import { User, Course, Job, JobApplication, Quiz, QuizResult, Certificate, PlacementRecord, ForumPost } from '../types';

export const INITIAL_STUDENT: User = {
  id: 'usr_student_1',
  name: 'Alex Rivera',
  email: 'alex.rivera@student.edu',
  role: 'student',
  phone: '+1 (555) 234-5678',
  college: 'National Institute of Technology',
  branch: 'Computer Science & Engineering',
  graduationYear: '2026',
  cgpa: 8.8,
  skills: ['React.js', 'Node.js', 'TypeScript', 'Tailwind CSS', 'SQL', 'Python'],
  resumeName: 'Alex_Rivera_Resume.pdf',
  resumeUrl: '#',
  bio: 'Final year CSE undergraduate passionate about Full Stack Development and Cloud Architecture. Active open-source contributor.',
};

export const INITIAL_ADMIN: User = {
  id: 'usr_admin_1',
  name: 'Dr. Sarah Jenkins',
  email: 'admin@skillbridge.edu',
  role: 'admin',
  phone: '+1 (555) 987-6543',
  college: 'SkillBridge Placement Office',
  skills: ['Placement Coordination', 'Curriculum Design', 'Corporate Relations'],
};

export const INITIAL_COURSES: Course[] = [
  {
    id: 'crs_1',
    title: 'Full Stack Web Development with React & Node.js',
    description: 'Master modern frontend and backend development with hands-on projects, Express REST APIs, state management, and Cloud deployments.',
    category: 'Web Development',
    duration: '8 Weeks',
    level: 'Intermediate',
    instructor: 'Prof. David Miller',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    pdfNotesUrl: '#download-notes-webdev',
    pdfNotesTitle: 'FullStack_WebDev_Complete_Cheatsheet.pdf',
    modulesCount: 12,
    enrolledStudentsCount: 1240,
    rating: 4.9,
    quizId: 'qz_js_1',
  },
  {
    id: 'crs_2',
    title: 'Data Structures & Algorithms in Java for Interviews',
    description: 'Comprehensive DSA preparation targeting top tier tech companies. Covers Big O notation, Trees, Graphs, Dynamic Programming, and LeetCode patterns.',
    category: 'Computer Science',
    duration: '10 Weeks',
    level: 'Advanced',
    instructor: 'Rohan Sharma (Ex-Google)',
    thumbnail: 'https://images.unsplash.com/photo-1516116211223-4258568880c6?w=600&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    pdfNotesUrl: '#download-notes-dsa',
    pdfNotesTitle: 'DSA_Interview_Mastery_Guide.pdf',
    modulesCount: 16,
    enrolledStudentsCount: 2150,
    rating: 4.8,
    quizId: 'qz_apt_1',
  },
  {
    id: 'crs_3',
    title: 'Python for Data Science & Machine Learning Fundamentals',
    description: 'Learn NumPy, Pandas, Matplotlib, Scikit-Learn, and build real data analysis models with real-world datasets.',
    category: 'Data Science',
    duration: '6 Weeks',
    level: 'Beginner',
    instructor: 'Dr. Anita Roy',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    pdfNotesUrl: '#download-notes-python',
    pdfNotesTitle: 'Python_DataScience_CrashCourse.pdf',
    modulesCount: 10,
    enrolledStudentsCount: 890,
    rating: 4.7,
    quizId: 'qz_py_1',
  },
  {
    id: 'crs_4',
    title: 'Database Systems & SQL Optimization for Software Engineers',
    description: 'In-depth coverage of Relational Databases, Indexing, Transactions, Query Optimization, and PostgreSQL architecture.',
    category: 'Database',
    duration: '5 Weeks',
    level: 'Intermediate',
    instructor: 'Mark Vance',
    thumbnail: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    pdfNotesUrl: '#download-notes-sql',
    pdfNotesTitle: 'SQL_Query_Optimization_Handout.pdf',
    modulesCount: 8,
    enrolledStudentsCount: 620,
    rating: 4.9,
    quizId: 'qz_sql_1',
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job_1',
    company: 'TechCorp Innovations',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    position: 'Software Development Engineer - I',
    salary: '$85,000 - $105,000 / year',
    location: 'San Francisco, CA (Hybrid)',
    type: 'Full-time',
    description: 'We are seeking an ambitious SDE-I to build scalable cloud microservices, develop modern frontend interfaces, and collaborate with product teams.',
    requirements: [
      'Strong grasp of Data Structures and Algorithms',
      'Proficiency in React.js, Node.js, or Java',
      'Knowledge of REST APIs and relational databases',
      'Bachelor’s degree in Computer Science or related field',
    ],
    skillsRequired: ['React.js', 'Node.js', 'TypeScript', 'SQL'],
    deadline: '2026-09-15',
    postedDate: '2026-08-01',
    applicantsCount: 42,
  },
  {
    id: 'job_2',
    company: 'CloudScale Dynamics',
    companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&auto=format&fit=crop&q=80',
    position: 'Frontend Developer Intern',
    salary: '$3,500 / month',
    location: 'Remote',
    type: 'Internship',
    description: 'Join our dynamic design system and UI engine team. Help build responsive web applications using Tailwind CSS and React component libraries.',
    requirements: [
      'Solid foundation in HTML5, CSS3, JavaScript (ES6+)',
      'Experience with React.js or Vue.js',
      'Eye for UI/UX detail and mobile responsiveness',
    ],
    skillsRequired: ['HTML5', 'CSS3', 'JavaScript', 'React.js', 'Tailwind CSS'],
    deadline: '2026-08-30',
    postedDate: '2026-08-02',
    applicantsCount: 88,
  },
  {
    id: 'job_3',
    company: 'DataPulse AI',
    companyLogo: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=100&auto=format&fit=crop&q=80',
    position: 'Junior Data Analyst',
    salary: '$72,000 - $82,000 / year',
    location: 'Austin, TX',
    type: 'Full-time',
    description: 'Analyze large datasets, write automated SQL queries, and construct interactive executive dashboards using Python and Tableau.',
    requirements: [
      'Hands-on SQL database query skills',
      'Experience with Python Pandas, NumPy, or R',
      'Strong analytical and statistical reasoning',
    ],
    skillsRequired: ['Python', 'SQL', 'Data Analytics', 'Pandas'],
    deadline: '2026-09-10',
    postedDate: '2026-07-28',
    applicantsCount: 29,
  },
  {
    id: 'job_4',
    company: 'CyberShield Systems',
    companyLogo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=100&auto=format&fit=crop&q=80',
    position: 'Backend Developer Trainee',
    salary: '$65,000 / year',
    location: 'New York, NY',
    type: 'Full-time',
    description: 'Work with our security infrastructure team constructing high-throughput API endpoints and OAuth security middleware.',
    requirements: [
      'Understanding of HTTP, REST, and authentication protocols',
      'Familiarity with Node.js/Express or Python FastAPI',
      'Knowledge of Git version control',
    ],
    skillsRequired: ['Node.js', 'Express', 'JWT', 'REST API'],
    deadline: '2026-09-01',
    postedDate: '2026-07-25',
    applicantsCount: 51,
  },
];

export const INITIAL_APPLICATIONS: JobApplication[] = [
  {
    id: 'app_1',
    jobId: 'job_1',
    jobTitle: 'Software Development Engineer - I',
    company: 'TechCorp Innovations',
    studentId: 'usr_student_1',
    studentName: 'Alex Rivera',
    studentEmail: 'alex.rivera@student.edu',
    appliedDate: '2026-08-02',
    status: 'Interview Scheduled',
    resumeUrl: '#',
    coverLetter: 'Excited to apply my Full Stack web skills and passion for scalable systems at TechCorp!',
    interviewDate: '2026-08-12 10:00 AM',
  },
  {
    id: 'app_2',
    jobId: 'job_2',
    jobTitle: 'Frontend Developer Intern',
    company: 'CloudScale Dynamics',
    studentId: 'usr_student_1',
    studentName: 'Alex Rivera',
    studentEmail: 'alex.rivera@student.edu',
    appliedDate: '2026-08-03',
    status: 'Shortlisted',
    resumeUrl: '#',
  },
];

export const INITIAL_QUIZZES: Quiz[] = [
  {
    id: 'qz_js_1',
    title: 'JavaScript Core Concepts & ES6+ Mastery',
    category: 'JavaScript',
    timeLimitMinutes: 10,
    questions: [
      {
        id: 'q_js_1',
        question: 'What is the output of `typeof null` in JavaScript?',
        options: ['"null"', '"undefined"', '"object"', '"boolean"'],
        correctOptionIndex: 2,
        explanation: 'Due to legacy implementation details in JS, `typeof null` returns `"object"`.',
      },
      {
        id: 'q_js_2',
        question: 'Which method creates a new array populated with the results of calling a function on every element?',
        options: ['forEach()', 'filter()', 'map()', 'reduce()'],
        correctOptionIndex: 2,
        explanation: '`map()` creates a new array by executing a callback on each item.',
      },
      {
        id: 'q_js_3',
        question: 'What does the `Promise.all()` method return when all promises resolve?',
        options: ['The first resolved promise value', 'An array of all resolved values', 'A boolean true', 'An object containing promise statuses'],
        correctOptionIndex: 1,
        explanation: '`Promise.all()` resolves with an array of values in the same order as input promises.',
      },
      {
        id: 'q_js_4',
        question: 'How do you declare a block-scoped variable in JavaScript?',
        options: ['var', 'let and const', 'global', 'scope'],
        correctOptionIndex: 1,
        explanation: '`let` and `const` introduce block-level scope, whereas `var` is function-scoped.',
      },
      {
        id: 'q_js_5',
        question: 'What keyword refers to the current object context in JavaScript execution?',
        options: ['self', 'this', 'parent', 'window'],
        correctOptionIndex: 1,
        explanation: 'The `this` keyword refers to the execution context object.',
      },
    ],
  },
  {
    id: 'qz_html_1',
    title: 'HTML5 Semantic Web & Accessibility Standard',
    category: 'HTML',
    timeLimitMinutes: 8,
    questions: [
      {
        id: 'q_html_1',
        question: 'Which element is used to specify a footer for a document or section?',
        options: ['<bottom>', '<footer_sec>', '<footer>', '<end>'],
        correctOptionIndex: 2,
        explanation: 'The `<footer>` element represents a footer for its nearest sectioning content.',
      },
      {
        id: 'q_html_2',
        question: 'What attribute specifies an alternative text for an image if it cannot be displayed?',
        options: ['title', 'alt', 'src', 'longdesc'],
        correctOptionIndex: 1,
        explanation: 'The `alt` attribute provides fallback textual description for images.',
      },
      {
        id: 'q_html_3',
        question: 'Which HTML5 element is used to embed native audio files?',
        options: ['<sound>', '<media>', '<audio>', '<music>'],
        correctOptionIndex: 2,
        explanation: 'The `<audio>` tag is used to embed sound content.',
      },
    ],
  },
  {
    id: 'qz_py_1',
    title: 'Python Data Structures & OOP Essentials',
    category: 'Python',
    timeLimitMinutes: 10,
    questions: [
      {
        id: 'q_py_1',
        question: 'Which data structure in Python is immutable?',
        options: ['List', 'Dictionary', 'Set', 'Tuple'],
        correctOptionIndex: 3,
        explanation: 'Tuples are immutable sequences in Python.',
      },
      {
        id: 'q_py_2',
        question: 'How do you define a function in Python?',
        options: ['function myFunc():', 'def myFunc():', 'fn myFunc():', 'create myFunc():'],
        correctOptionIndex: 1,
        explanation: 'The `def` keyword introduces a function definition in Python.',
      },
      {
        id: 'q_py_3',
        question: 'What is list comprehension syntax in Python?',
        options: ['[x for x in iterable]', '{x in iterable}', 'x.map(iterable)', 'for(x in iterable)'],
        correctOptionIndex: 0,
        explanation: '`[expression for item in iterable]` is standard list comprehension format.',
      },
    ],
  },
  {
    id: 'qz_sql_1',
    title: 'SQL Relational Queries & Joins Quiz',
    category: 'SQL',
    timeLimitMinutes: 10,
    questions: [
      {
        id: 'q_sql_1',
        question: 'Which SQL clause is used to filter records after aggregation with GROUP BY?',
        options: ['WHERE', 'HAVING', 'FILTER', 'ORDER BY'],
        correctOptionIndex: 1,
        explanation: '`HAVING` filters group rows after `GROUP BY` execution.',
      },
      {
        id: 'q_sql_2',
        question: 'Which join returns all matching rows from both tables, plus unmatched rows from either side?',
        options: ['INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'FULL OUTER JOIN'],
        correctOptionIndex: 3,
        explanation: '`FULL OUTER JOIN` combines the results of both left and right outer joins.',
      },
    ],
  },
  {
    id: 'qz_apt_1',
    title: 'General Aptitude & Logical Reasoning for Placements',
    category: 'Aptitude',
    timeLimitMinutes: 10,
    questions: [
      {
        id: 'q_apt_1',
        question: 'If a train traveling at 60 km/h passes a pole in 9 seconds, what is the length of the train in meters?',
        options: ['120 meters', '150 meters', '180 meters', '200 meters'],
        correctOptionIndex: 1,
        explanation: 'Speed = 60 * (5/18) = 50/3 m/s. Length = Speed * Time = (50/3) * 9 = 150 meters.',
      },
      {
        id: 'q_apt_2',
        question: 'Find the next number in sequence: 2, 6, 12, 20, 30, ?',
        options: ['38', '40', '42', '46'],
        correctOptionIndex: 2,
        explanation: 'Differences are 4, 6, 8, 10. Next difference is 12 -> 30 + 12 = 42.',
      },
    ],
  },
];

export const INITIAL_QUIZ_RESULTS: QuizResult[] = [
  {
    id: 'qres_1',
    quizId: 'qz_js_1',
    quizTitle: 'JavaScript Core Concepts & ES6+ Mastery',
    studentId: 'usr_student_1',
    studentName: 'Alex Rivera',
    score: 5,
    totalQuestions: 5,
    percentage: 100,
    completedAt: '2026-08-03',
  },
  {
    id: 'qres_2',
    quizId: 'qz_html_1',
    quizTitle: 'HTML5 Semantic Web & Accessibility Standard',
    studentId: 'usr_student_2',
    studentName: 'Sophia Lin',
    score: 3,
    totalQuestions: 3,
    percentage: 100,
    completedAt: '2026-08-01',
  },
  {
    id: 'qres_3',
    quizId: 'qz_py_1',
    quizTitle: 'Python Data Structures & OOP Essentials',
    studentId: 'usr_student_3',
    studentName: 'Rohan Mehta',
    score: 2,
    totalQuestions: 3,
    percentage: 67,
    completedAt: '2026-07-30',
  },
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    id: 'cert_1',
    studentId: 'usr_student_1',
    studentName: 'Alex Rivera',
    courseId: 'crs_1',
    courseTitle: 'Full Stack Web Development with React & Node.js',
    issueDate: '2026-08-03',
    verificationCode: 'SKILL-2026-9812-781A',
    grade: 'Excellence (A+)',
  },
];

export const INITIAL_PLACEMENTS: PlacementRecord[] = [
  {
    id: 'plc_1',
    company: 'TechCorp Innovations',
    visitDate: '2026-09-20',
    rolesOffered: 'SDE-I, Backend Engineer',
    packageLPA: 12.5,
    totalSelected: 14,
    eligibilityCGPA: 7.5,
    status: 'Upcoming',
    interviewProcess: 'Online Assessment -> Technical Round 1 -> Technical Round 2 -> HR Culture Fit',
  },
  {
    id: 'plc_2',
    company: 'CloudScale Dynamics',
    visitDate: '2026-08-10',
    rolesOffered: 'Frontend Intern, Fullstack Developer',
    packageLPA: 9.0,
    totalSelected: 8,
    eligibilityCGPA: 7.0,
    status: 'Ongoing',
    interviewProcess: 'Coding Round -> Systems Design -> HR Interview',
  },
  {
    id: 'plc_3',
    company: 'Global Logic Analytics',
    visitDate: '2026-07-15',
    rolesOffered: 'Data Engineer, Business Analyst',
    packageLPA: 10.2,
    totalSelected: 22,
    eligibilityCGPA: 6.8,
    status: 'Completed',
    interviewProcess: 'Aptitude & SQL Test -> Technical Interview -> Managerial Round',
  },
];

export const INITIAL_FORUM_POSTS: ForumPost[] = [
  {
    id: 'post_1',
    authorId: 'usr_student_1',
    authorName: 'Alex Rivera',
    authorRole: 'student',
    title: 'How to prepare effectively for System Design rounds in SDE-1 campus placements?',
    content: 'Hi everyone! I have an upcoming technical round with TechCorp. What core concepts should final year students focus on for low-level & high-level system design? (e.g. Caching, Database Indexing, Load Balancers)',
    tags: ['System Design', 'Placements', 'Interview Prep'],
    createdAt: '2026-08-02',
    likes: 18,
    likedBy: [],
    comments: [
      {
        id: 'cmt_1',
        authorId: 'usr_admin_1',
        authorName: 'Dr. Sarah Jenkins',
        authorRole: 'admin',
        content: 'Focus heavily on database schema design, indexing strategies, and understanding trade-offs between SQL vs NoSQL. Review the Database Systems course on SkillBridge!',
        createdAt: '2026-08-02',
        likes: 5,
      },
      {
        id: 'cmt_2',
        authorId: 'usr_student_2',
        authorName: 'Sophia Lin',
        authorRole: 'student',
        content: 'Also practice drawing block diagrams clearly and talking through your trade-offs out loud during the interview!',
        createdAt: '2026-08-03',
        likes: 3,
      },
    ],
  },
  {
    id: 'post_2',
    authorId: 'usr_student_2',
    authorName: 'Sophia Lin',
    authorRole: 'student',
    title: 'Top 10 LeetCode patterns for dynamic programming questions',
    content: 'Created a short compilation of DP patterns like 0/1 Knapsack, Unbounded Knapsack, LCS, and Fibonacci variations that frequently show up in college coding assessments.',
    tags: ['DSA', 'LeetCode', 'Algorithms'],
    createdAt: '2026-07-29',
    likes: 34,
    likedBy: [],
    comments: [],
  },
];
